# scene
scene_id: /home/meng/habitat-sim/data/scene_datasets/habitat-test-scenes/van-gogh-room.glb

# robot
agent_initial_position: [0, 0, 0]
agent_initial_rotation: [0, 90, 0]
agent_target_pos: [0.5, 0.5, 0]

# observation space
color_sensor: true
depth_sensor: true
semantic_sensor: false
image_width: 224
image_height: 224
normalize_depth: false
min_depth: 0
max_depth: 1
dictionary_observation_space: false


# task
task: navigate_goal_fixed
dark_mode: true

# reward
use_goal_dist_reward: false
goal_dist_reward_weight: 1.0 # should > 0

success_reward: 10.0
dist_tol: 0.25 # l2 distance in meter

collision_penalty: -1.0 #-1000.0
time_elapse_reward: 0.0 #-1.0
out_of_bound_reward: -1000.0


# episode termination condition
max_step: 200
max_collisions_allowed: 200





