# scene
scene_id: /home/meng/habitat-sim/data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
#scene_id: /home/meng/habitat-sim/data/replica/stages/frl_apartment_stage.glb
#scene_id: /home/meng/habitat-sim/data/replica/stages/Stage_v3_sc0_staging.glb
#scene_id: /dataset/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb

# robot
agent_initial_position: [3, 0, 1]
agent_initial_rotation: [0, 70, 0] #[0, 90, 0]
forward_resolution: 0.25
rotate_resolution: 10


# observation space
color_sensor: true
depth_sensor: true
semantic_sensor: false
image_width: 224
image_height: 224
normalize_depth: false
min_depth: 0
max_depth: 1
dictionary_observation_space: false


# task
task: point_goal_navigation
dark_mode: false
flashlight_z: 0.2
goal_position: [4, 0, -1]
random_goal: false
random_start: false

# reward
use_goal_dist_reward: false
goal_dist_reward_weight: 1.0 # should > 0

success_reward: 10.0
dist_tol: 0.25 # l2 distance in meter

collision_penalty: -1.0 #-1000.0
time_elapse_reward: 0.0 #-1.0
out_of_bound_reward: -1000.0


# episode termination condition
max_steps_per_episode: 200
max_collisions_per_episode: 200

# others
save_observations: false





