# scene
scene_id: /home/meng/habitat-sim/data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
#scene_id: /home/meng/habitat-sim/data/replica/stages/frl_apartment_stage.glb
#scene_id: /home/meng/habitat-sim/data/replica/stages/Stage_v3_sc0_staging.glb
#scene_id: /dataset/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb

# robot
agent_initial_position: [3, 0, 1]
agent_initial_rotation: [0, 70, 0] #[0, 90, 0]
forward_resolution: 0.25
rotate_resolution: 10


# observation space
color_sensor: true
depth_sensor: true
semantic_sensor: false
image_width: 224
image_height: 224
normalize_depth: false
min_depth: 0
max_depth: 1
dictionary_observation_space: true


# task
dark_mode: true
flashlight_z: 0.2


# goal
goal_conditioned: true
goal_format: pointgoal # imagegoal
goal_coord_system: polar  #  cartesian
goal_dimension: 2
goal_position: [4, 0, -1]
random_goal: true
random_start: false

# reward
success_distance: 0.1 # l2 distance in meter
success_reward: 2.5 
slack_reward: -1e-4

# episode termination condition
max_steps_per_episode: 400
max_collisions_per_episode: 200

# others
save_observations: false
seed: 1
visual_encoder: ResNet # CNN 
gpu_id: 0








